device_tracker:
- platform: unifi
  host: 192.168.2.163
  username: unifi_username
  password: unifi_password
  verify_ssl: False
telegram_bot:
  platform: polling
  api_key: telegram_key
  allowed_chat_ids:
  - telegram_chatID_Alok
hangouts: ''
notify:
- platform: ios
- platform: hangouts
  name: alok_hangouts
  default_conversations:
  - id: hangouts_alok
- platform: hangouts
  name: rashmi_hangouts
  default_conversations:
  - id: hangouts_rashmi
- platform: hangouts
  name: parents_hangouts
  default_conversations:
  - id: hangouts_rashmi
  - id: hangouts_alok
- platform: pushbullet
  api_key: pushbullet_key
  name: pushbullet
- name: telegram
  platform: telegram
  api_key: telegram_key
  chat_id: telegram_chatID_Alok
- platform: ecobee
  name: ecobee
- platform: group
  name: iOS
  services:
  - service: ios_alokiosiphone
  - service: ios_rashmiappiphone
- platform: group
  name: ios_abode_updates
  services:
  - service: ios_alokiosiphone
    data:
      title: Enable Abode updates?
      data:
        push:
          badge: 0
          category: abode_updates
- platform: nfandroidtv
  name: Shield
  host: 192.168.2.28
- platform: command_line
  name: Echo Dot
  command: /home/homeassistant/.homeassistant/shell_scripts/alexa_wrapper.sh -d 'Echo Dot Gen2'
logger:
  default: error
  logs:
    homeassistant.components.image_processing: critical
    homeassistant.components.camera.synology: critical
    homeassistant.components.camera.generic: critical
    homeassistant.components.sensor.wunderground: critical
    homeassistant.components.sensor.pi_hole: critical
    homeassistant.components.media_player: critical
    homeassistant.components.telegram_bot: critical
    homeassistant.components.scene.lifx_cloud: critical
    homeassistant.components.sensor.darksky: critical
    pychromecast.socket_client: critical
    aiohttp.access: critical
    aiohttp.server: critical
    haffmpeg.core: critical
    homeassistant.core: critical
    pywemo.ouimeaux_device: critical
    pywemo.ssdp: critical
    homeassistant.helpers.entity: critical
    custom_components.sensor.life360: critical
    custom_components.alarm_control_panel: critical
    homeassistant.components.http.ban: warning
    homeassistant.components.python_script: warning
    custom_components.sensor.personalcapital: debug
tts:
- platform: google
  cache: true
  cache_dir: /home/homeassistant/.homeassistant/tts
  time_memory: 300
remote:
- platform: harmony
  name: livingroom
  host: 192.168.2.152
google:
  client_id: gcal_client_id
  client_secret: gcal_client_secret
scene:
  platform: lifx_cloud
  token: lifx_key
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: mqtt_username
  password: mqtt_password
alexa: ''
dialogflow: ''
intent_script.yaml: {}
ios.yaml: {}
alert.yaml: {}
automations.yaml: {}
cover.yaml: {}
groups.yaml: {}
scripts.yaml: {}
sensor.yaml: {}
switches.yaml: {}
binary_sensor.yaml: {}
input_select.yaml: {}
input_boolean.yaml: {}
input_number.yaml: {}
input_text.yaml: {}
frontend.yaml: {}
recorder.yaml: {}
logbook.yaml: {}
history.yaml: {}
...
