homeassistant:
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
  - type: legacy_api_password
  latitude: latitude_home
  longitude: longitude_home
  elevation: 322
  name: Home
  temperature_unit: F
  time_zone: America/New_York
  unit_system: imperial
  customize.yaml:
    cloud:
      alexa:
        filter:
          include_entities:
          - light.living_room_lights
          - light.master_lights
          - input_boolean.abodeupdate
          - light.gateway_light_34ce00813670
          - light.kitchen_lights
          - light.lifx5
          - switch.driveway
          - switch.garage_relay_switch
          - switch.wemoporch
          - script.tv_youtube_on
          include_domains:
          - cover
    cloud2:
      alexa:
        filter:
          include_entities:
          - light.living_room_lights
          - light.master_lights
          - input_boolean.abodeupdate
          - light.gateway_light_34ce00813670
          - light.kitchen_lights
          - light.lifx5
          - switch.driveway
          - switch.garage_relay_switch
          - switch.wemoporch
          - script.tv_youtube_on
          include_domains:
          - cover
  customize_glob.yaml: {}
  packages: packages
  whitelist_external_dirs:
  - /home/homeassistant/.homeassistant/downloads
  - /tmp
  - /home/homeassistant/.homeassistant/downloads/camera/
lovelace:
  mode: yaml
updater:
  include_used_components: true
python_script: ''
weather:
- platform: yweather
  name: yweather
  woeid: woeid
panel_custom:
- name: no-love
  sidebar_title: No love
  sidebar_icon: mdi:heart-off
  webcomponent_path: /home/homeassistant/.homeassistant/panels/no-love.html
zone:
  name: Home
  latitude: latitude_home
  longitude: longitude_home
  radius: 200
  icon: mdi:home
zone 2:
  name: Buckhead
  latitude: latitude_buckhead
  longitude: longitude_buckhead
  radius: 200
  icon: mdi:school
zone 3:
  name: Downtown
  latitude: latitude_downtown
  longitude: longitude_downtown
  radius: 200
  icon: mdi:school
zwave:
  usb_path: /dev/ttyACM0
  network_key: zwave_network_key
hue:
  bridges:
  - host: 192.168.2.229
    allow_hue_groups: false
lifx:
  light: ''
light:
- platform: mqtt
  name: Kitchen Lights
  state_topic: smartthings/Kitchen/switch
  command_topic: smartthings/Kitchen/switch
  payload_on: on
  payload_off: off
  brightness_state_topic: smartthings/Kitchen/level
  brightness_command_topic: smartthings/Kitchen/level
  brightness_scale: 99
  brightness_value_template: '{{ value }}'
  retain: true
  optimistic: false
- platform: group
  name: Master Lights
- platform: sdds
  name: asdsad
arlo:
  username: arlo_user
  password: arlo_password
  scan_interval: 120
tuya:
  username: tuya_user
  password: tuya_password
  country_code: 1
alarm_control_panel:
- platform: ifttt
  name: ArloHome
  event_arm_away: arlo_alarm_arm_away
  event_disarm: arlo_alarm_disarm
  optimistic: true
xiaomi_aqara:
  gateways:
  - key: xiaomikey
    host: 192.168.2.82
abode:
  username: abode_username
  password: abode_password
ring:
  username: ring_username
  password: ring_password
bloomsky:
  api_key: bloomsky_key
ecobee:
  api_key: ecobee_key
  hold_temp: True
shell_command:
  image_classify: bash /home/homeassistant/.homeassistant/shell_scripts/image_classification.sh "{{camera}}"
  facebox: bash /home/homeassistant/.homeassistant/shell_scripts/facebox.sh "{{camera}}"
rest_command:
  youtube:
    url: http://192.168.2.252:8001/api/v2/applications/111299001912
    method: post
  netflix:
    url: http://192.168.2.252:8001/ws/apps/Netflix
    method: post
  plex:
    url: http://192.168.2.252:8001/api/v2/applications/kIciSQlYEM.plex
    method: post
media_extractor: ''
config: ''
cloud:
  alexa:
    filter:
      include_entities:
      - light.living_room_lights
      - light.master_lights
      - input_boolean.abodeupdate
      - light.gateway_light_34ce00813670
      - light.kitchen_lights
      - light.lifx5
      - switch.driveway
      - switch.garage_relay_switch
      - switch.wemoporch
      - script.tv_youtube_on
      include_domains:
      - cover
    entity_config:
      light.gateway_light_34ce00813670:
        name: Gateway Light
        description: Xiaomi Gateway Light
      script.tv_youtube_on:
        name: Youtube
        description: Youtube on
  google_actions:
    filter:
      include_entities:
      - script.tv_youtube_on
      - switch.wemoporch
      - switch.driveway
      - switch.wemoinsight
      include_domains:
      - cover
      - light
      exclude_entities:
      - light.gateway_light_34ce00813670
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
      - light.lifx3
      - light.lifxnrguest
      - light.lifxnrkitchen
    entity_config:
      light.living_room_lights:
        room: living room
      light.master_lights:
        room: master bedroom
      switch.driveway:
        room: driveway
      switch.wemoporch:
        name: Porch Lights
        room: porch
      light.kitchen_lights:
        room: kitchen
      light.lifx5:
        room: garage
      switch.wemoinsight:
        name: Wemo Insight
        room: office
      script.tv_youtube_on:
        name: Youtube
        room: living room
google_assistant:
  project_id: google_project_id
  api_key: google_project_api_key
  expose_by_default: false
  exposed_domains:
  - cover
  entity_config:
    light.living_room_lights:
      expose: true
      room: living room
    light.master_lights:
      expose: true
      room: master bedroom
    switch.driveway:
      expose: true
      room: driveway
    switch.wemoporch:
      expose: true
      name: Porch Lights
      room: porch
    light.kitchen_lights:
      expose: true
      room: kitchen
    light.lifx5:
      expose: true
      room: garage
    switch.wemoinsight:
      expose: true
      name: Wemo Insight
      room: office
    script.tv_youtube_on:
      expose: True
      name: Youtube
      room: living room
map: ''
downloader:
  download_dir: downloads
http:
  api_password: http_password
  ssl_certificate: ssl_certificate
  ssl_key: ssl_key
  base_url: base_url
  ip_ban_enabled: True
  login_attempts_threshold: 2
  trusted_networks:
  - 192.168.2.0/24
discovery:
  ignore:
  - apple_tv
  - panasonic_viera
proximity:
  alok:
    devices:
    - device_tracker.meta_alok
    tolerance: 50
    unit_of_measurement: mi
  rashmi:
    devices:
    - device_tracker.meta_rashmi
    tolerance: 50
    unit_of_measurement: mi
conversation: ''
ffmpeg: ''
camera:
- platform: bloomsky
- platform: synology
  url: http://192.168.2.113:5000/
  username: synology_username
  password: synology_password
  timeout: 15
  verify_ssl: False
- platform: arlo
- platform: ring
- platform: local_file
  name: Driveway TF
  file_path: /home/homeassistant/.homeassistant/downloads/camera/driveway_latest.jpg
- platform: local_file
  name: Porch TF
  file_path: /home/homeassistant/.homeassistant/downloads/camera/porch_latest.jpg
- platform: local_file
  name: Patio TF
  file_path: /home/homeassistant/.homeassistant/downloads/camera/patio_latest.jpg
- platform: local_file
  name: Backyard TF
  file_path: /home/homeassistant/.homeassistant/downloads/camera/backyard_latest.jpg
- platform: generic
  still_image_url: meteogram_png_url
  name: Meteogram
ifttt:
  key: ifttt_key
image_processing:
- platform: facebox
  scan_interval: 10000
  ip_address: 192.168.2.212
  port: 8082
  source:
  - entity_id: camera.patio
  - entity_id: camera.porch
  - entity_id: camera.backyard
  - entity_id: camera.driveway
- platform: tagbox
  scan_interval: 10000
  ip_address: 192.168.2.212
  confidence: 50
  port: 8081
  source:
  - entity_id: camera.patio
  - entity_id: camera.porch
  - entity_id: camera.backyard
  - entity_id: camera.driveway
- platform: opencv_darknet
  name: Camera Object Detection
  scan_interval: 10000
  source:
  - entity_id: camera.patio
  - entity_id: camera.porch
  - entity_id: camera.backyard
  - entity_id: camera.driveway
  options:
    detect_model: /home/homeassistant/.homeassistant/deps/yolov3-tiny.cfg
    weights: /home/homeassistant/.homeassistant/deps/yolov3-tiny.weights
    labels: /home/homeassistant/.homeassistant/deps/coco.names
    confidence: 0.55
- platform: tensorflow
  confidence: 75
  scan_interval: 10000
  source:
  - entity_id: camera.patio
  file_out:
  - /home/homeassistant/.homeassistant/downloads/camera/{{ camera_entity.split('.')[1] }}_latest.jpg
  model:
    graph: /home/homeassistant/.homeassistant/deps/frozen_inference_graph.pb
    model_dir: /home/homeassistant/.homeassistant/deps/tensorflow
    labels: /home/homeassistant/.homeassistant/deps/tensorflow/object_detection/data/mscoco_label_map.pbtxt
    categories:
    - person
- platform: tensorflow
  confidence: 75
  scan_interval: 10000
  source:
  - entity_id: camera.backyard
  - entity_id: camera.driveway
  - entity_id: camera.porch
  file_out:
  - /home/homeassistant/.homeassistant/downloads/camera/{{ camera_entity.split('.')[1] }}_latest.jpg
  model:
    graph: /home/homeassistant/.homeassistant/deps/frozen_inference_graph.pb
    model_dir: /home/homeassistant/.homeassistant/deps/tensorflow
    labels: /home/homeassistant/.homeassistant/deps/tensorflow/object_detection/data/mscoco_label_map.pbtxt
    categories:
    - category: person
      area:
        top: 0.20
    - bus
    - category: truck
      area:
        top: 0.20
        right: 0.20
    - category: car
      area:
        top: 0.20
        right: 0.20
sonos:
  media_player:
    hosts:
    - 192.168.2.150
    - 192.168.2.253
sun: ''
media_player:
- platform: kodi
  host: 192.168.2.28
  port: 8080
  name: Kodi NSTV
  username: kodi_username
  password: kodi_password
- platform: samsungtv
  host: 192.168.2.252
  name: Living Room TV
  mac: samsungtvmac
  port: 8001
  timeout: 5
- platform: alexa
  email: amazon_user
  password: amazon_pass
  url: amazon.com
geofency: ''
owntracks:
  max_gps_accuracy: 200
device_tracker:
- platform: unifi
  host: 192.168.2.163
  username: unifi_username
  password: unifi_password
  verify_ssl: False
telegram_bot:
  platform: polling
  api_key: telegram_key
  allowed_chat_ids:
  - telegram_chatID_Alok
hangouts: ''
notify:
- platform: ios
- platform: hangouts
  name: alok_hangouts
  default_conversations:
  - id: hangouts_alok
- platform: hangouts
  name: rashmi_hangouts
  default_conversations:
  - id: hangouts_rashmi
- platform: hangouts
  name: parents_hangouts
  default_conversations:
  - id: hangouts_rashmi
  - id: hangouts_alok
- platform: pushbullet
  api_key: pushbullet_key
  name: pushbullet
- name: telegram
  platform: telegram
  api_key: telegram_key
  chat_id: telegram_chatID_Alok
- platform: ecobee
  name: ecobee
- platform: group
  name: iOS
  services:
  - service: ios_alokiosiphone
  - service: ios_rashmiappiphone
- platform: group
  name: ios_abode_updates
  services:
  - service: ios_alokiosiphone
    data:
      title: Enable Abode updates?
      data:
        push:
          badge: 0
          category: abode_updates
- platform: nfandroidtv
  name: Shield
  host: 192.168.2.28
- platform: command_line
  name: Echo Dot
  command: /home/homeassistant/.homeassistant/shell_scripts/alexa_wrapper.sh -d 'Echo Dot Gen2'
logger:
  default: error
  logs:
    homeassistant.components.image_processing: critical
    homeassistant.components.camera.synology: critical
    homeassistant.components.camera.generic: critical
    homeassistant.components.sensor.wunderground: critical
    homeassistant.components.sensor.pi_hole: critical
    homeassistant.components.media_player: critical
    homeassistant.components.telegram_bot: critical
    homeassistant.components.scene.lifx_cloud: critical
    homeassistant.components.sensor.darksky: critical
    pychromecast.socket_client: critical
    aiohttp.access: critical
    aiohttp.server: critical
    haffmpeg.core: critical
    homeassistant.core: critical
    pywemo.ouimeaux_device: critical
    pywemo.ssdp: critical
    homeassistant.helpers.entity: critical
    custom_components.sensor.life360: critical
    custom_components.alarm_control_panel: critical
    homeassistant.components.http.ban: warning
    homeassistant.components.python_script: warning
    custom_components.sensor.personalcapital: debug
tts:
- platform: google
  cache: true
  cache_dir: /home/homeassistant/.homeassistant/tts
  time_memory: 300
remote:
- platform: harmony
  name: livingroom
  host: 192.168.2.152
google:
  client_id: gcal_client_id
  client_secret: gcal_client_secret
scene:
  platform: lifx_cloud
  token: lifx_key
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: mqtt_username
  password: mqtt_password
alexa: ''
dialogflow: ''
intent_script.yaml: {}
ios.yaml: {}
alert.yaml: {}
automations.yaml: {}
cover.yaml: {}
groups.yaml: {}
scripts.yaml: {}
sensor.yaml: {}
switches.yaml: {}
binary_sensor.yaml: {}
input_select.yaml: {}
input_boolean.yaml: {}
input_number.yaml: {}
input_text.yaml: {}
frontend.yaml: {}
recorder.yaml: {}
logbook.yaml: {}
history.yaml: {}
...
